### PR TITLE
allow react 17

### PR DESCRIPTION
**Pull request by trajano**

### CODE REVIEW

**Comment by kwnstantina** [comment]
Is it possible to merge this PR?

**Comment by pgdavidApodis** [comment]
Would be great !

**Comment by nicobermudez** [comment]
Bump. Need this to be able to use Expo.

**Comment by nicobermudez** [comment]
@iamacup any updates on this one? Seems like a simple update

**Comment by vini-coelho** [comment]
Any updates on this one? Need it to upgrade to latest Salesforce SDK.

**Comment by Tjerk-Haaye-Henricus** [comment]
Hey there, Any Update ? Would be great if this would be merged

**Comment by NilsBaumgartner1994** [comment]
push

**Review by chrisglein — APPROVED** [review]

**Comment by chrisglein** [comment]
@imacup There are many versions of this same change, coming from the error I imagine most of us are seeing:
```
warning " > react-native-markdown-display@7.0.0-alpha.2" has incorrect peer dependency "react@^16.2.0".
```
And if you `npm list react`, you'll see:
```
+-- react-native-markdown-display@7.0.0-alpha.2
| `-- react@18.2.0 deduped invalid: "^16.2.0" from node_modules/react-native-markdown-display
```

Other PRs doing similar things:
- https://github.com/iamacup/react-native-markdown-display/pull/147
- https://github.com/iamacup/react-native-markdown-display/pull/185 (has changes from a [fork](https://www.npmjs.com/package/react-native-markdown-display-updated) that probably shouldn't be applied?)

But of all of them... this one is the simplest. Seems like the least controversial merge.

**Comment by iamacup** [comment]
I have merged, will push a release shortly.

@chrisglein would you (or anyone else in this thread) be able to help fix this package up a bit?

I have not used React or React Native since hooks came in so i am really not best placed for it anymore.

**Pull request merged**
