### PR TITLE
Fixed TypeScript type definitions

### PR DESCRIPTION
**Pull request by lukeramsden**
#56
Just thought I'd try help out and make a PR for all the changes I made to the TypeScript defs so that I could copy all of the renderRules in to my project (as I use custom components for everything). I've no experience with the actual package code so would be good if someone can check my work to make sure it matches what's actually happening in the library. Also, there's still an issue where I get this error:

```
Type '{ unknown: (_node: ASTNode, _children: ReactNode[], _parent: ASTNode[], _styles: any) => null; body: (node: ASTNode, children: ReactNode[], parent: ASTNode[], styles: any) => Element; ... 33 more ...; span: (node: ASTNode, children: ReactNode[], parent: ASTNode[], styles: any) => Element; }' is not assignable to type 'RenderRules'.
  Type '{ unknown: (_node: ASTNode, _children: ReactNode[], _parent: ASTNode[], _styles: any) => null; body: (node: ASTNode, children: ReactNode[], parent: ASTNode[], styles: any) => Element; ... 33 more ...; span: (node: ASTNode, children: ReactNode[], parent: ASTNode[], styles: any) => Element; }' is not assignable to type '{ [name: string]: RenderFunction; }'.
    Property 'image' is incompatible with index signature.
      Type '(node: ASTNode, children: ReactNode[], parent: ASTNode[], styles: any, allowedImageHandlers: string[], defaultImageHandler: string) => Element | null' is not assignable to type 'RenderFunction'.ts(2322)
```

Which is because for some reason the function signature overrides work for link and blocklink but I have no idea why just yet.

### CODE REVIEW

**Comment by iamacup** [comment]
Hey, thanks so much for this - looks great

There are a couple of other changes that need to go in as well in line with 6.1.0 which is going out shortly - i will do 6.1.1 to fix TS defs once they are ready - do you want to put them in as part of your pull?


These all need to go completely:

```
interface PluginContainerResult<A> extends Array<any> {
  0: A;
}

export class PluginContainer<A> {
  constructor(plugin: A, ...options: any[]);
  toArray(): PluginContainerResult<A>;
}

export function blockPlugin(md: any, name: string, options: object): any;
```

As does

```
  plugins?: Array<PluginContainer<any>>;
```

Any ideas yet what the remaining error you mentioned ? :)

**Comment by lukeramsden** [comment]
I've managed to fix the error, but it's not pretty...

For _some reason_, the error doesn't appear if I remove the last parameter from `RenderImageFunction`, _or_ I add an empty parameter to `RenderFunction`:

```ts
export type RenderFunction = (
  node: ASTNode,
  children: ReactNode[],
  parentNodes: ASTNode[],
  styles: any,
  styleObj?: any,
  _?: any, // non-existent parameter
) => ReactNode;
```

Seems like if the function type for the `RenderRules` index signature has less arguments than one of the overrides, it breaks - but then `RenderLinkFunction` only has 5 while the other two have 6, so it doesn't go the other way. I've already done a commit to remove the plugin defs, and I'll commit these changes and it should all be ok from what I've seen - I don't know if there's any other issues with the defs because I haven't tried any of the more advanced functionality, but if there is I'll fix them in another PR at a later date.

I'm going to see if I can ask around in the TS community about this, as it seems like a bug to me, although they may be able to shed some light on it.

**Comment by lukeramsden** [comment]
Ok I'm fairly happy with that now, that should work with any future override types we may need to add. You may want to do a squash merge because I've done quite a few commits to get it working. I still don't quite understand why it has an issue with the override function type having more arguments but for now, it works.

**Comment by iamacup** [comment]
This looks great, i will merge this week / weenend and push out another release - thanks so much!

**Comment by lukeramsden** [comment]
My pleasure! Hopefully I'll get a chance to contribute more.

**Comment by LuisRodriguezLD** [comment]
If I may add, Webstorm complains that `MarkdownIt` is not being exported from this package. Can export the `MarkdownIt` type? Maybe something like: 
```javascript
export const MarkdownIt: MarkdownIt;
```

**Comment by lukeramsden** [comment]
I'm pretty sure that should fix it

**Pull request merged**
